### ISSUE TITLE
Задайте пожалуйста родительскому div - id или class

### ISSUE THREAD

**Issue by proteye** [QIWI-API/qiwi-invoicing-popup#2]
Здравствуйте.
Задайте, пожалуйста, родительскому div какой-нибудь id или class, чтобы к нему можно было обратиться и поправить некоторые стили под конкретный проект.

**Comment by Khromushkin** [comment]
Здравствуйте.
Добавили родительскому div id qiwi-checkout-popup 3 июля 2019: https://github.com/QIWI-API/bill-payments-popup-js-sdk/commit/90dd787e191d0c3b4bc7e512ffc16a6b82615870
Спасибо за обратную связь.
Наверное, пришло время закрыть issue =)
