### ISSUE TITLE
Uncaught ReferenceError: invoiceParams is not defined

### ISSUE THREAD

**Issue by pyankoff** [QIWI-API/qiwi-invoicing-popup#3]
После успешной оплаты вылетает ошибка:
```
Uncaught ReferenceError: invoiceParams is not defined
```

Вот эта строчка:
https://github.com/QIWI-API/bill-payments-popup-js-sdk/blob/master/src/index.js#L22

**Comment by eeeman1** [comment]
точно такая же фигня, разрабы походу студенты на подработке, вообще болт забили

**Comment by eeeman1** [comment]
пишу им уже 2 недели в поддержку, а они только болт сосут и всё говорят что заявка в работе, это на сколько там шлаковые разрабы, что до сих пор не могут такую фигню пофиксить

**Comment by eeeman1** [comment]
короче пока эти дауны там пытаются найти прогеров которые это зафиксят, я склонировал репу, просто обновил версии qs и moment, собрал бандл и ошибка пропала, теперь юзаю свой локальный бандл

**Comment by Khromushkin** [comment]
Исправили ошибку.
