### ISSUE TITLE
Ошибка при успешной оплате

### ISSUE THREAD

**Issue by fakemancat** [QIWI-API/qiwi-invoicing-popup#5]
Скрины прилагаются:
![TeamViewer_5EjK8KtwUv](https://user-images.githubusercontent.com/33839807/74181150-89c33880-4c62-11ea-94b8-86bd6e004a71.png)
![TeamViewer_jPgYknHiFP](https://user-images.githubusercontent.com/33839807/74181156-8b8cfc00-4c62-11ea-8698-040508458be6.png)
![TeamViewer_61DHf382ek](https://user-images.githubusercontent.com/33839807/74181159-8cbe2900-4c62-11ea-82e7-0ff07cf4e463.png)

Действия:
- Открыл popup
- Выполнил оплату в размере 1 руб.
- После оплаты popup закрылся, а в консоль выпали ошибки

**Comment by eeeman1** [comment]
подтверждаю, та же фигня, когда будет исправлено?
![Снимок](https://user-images.githubusercontent.com/26044998/76450176-69f86f00-63de-11ea-90ac-04309f6549e0.PNG)

**Comment by eeeman1** [comment]
короче пока эти дауны там пытаются найти прогеров которые это зафиксят, я склонировал репу, просто обновил версии qs и moment, собрал бандл и ошибка пропала, теперь юзаю свой локальный бандл

**Comment by fakemancat** [comment]
Похоже они просто забили и всё...
Спасибо за репу :)

**Comment by fakemancat** [comment]
Слушай, можешь мне его скинуть или направить хотя бы где исправлять?

**Comment by eeeman1** [comment]
> 
> 
> Слушай, можешь мне его скинуть или направить хотя бы где исправлять?

так ты склонируй их проект, qs и moment обнови через ярн или нпм до последней версии и запусти build, тебе соберется бандл , его и подключай к себе вместо их бандла по ссылке

**Comment by Khromushkin** [comment]
Исправили ошибку.
